fix all sorts of stuff with dgl-create-chroot
git-svn-id: svn://katsu.triplehelix.org/dgamelaunch/trunk@344 db0b04b0-f4d1-0310-9a6d-de3e77497b0e

diff --git a/dgl-create-chroot b/dgl-create-chroot
--- a/dgl-create-chroot
+++ b/dgl-create-chroot
@@ -23,21 +23,26 @@ playground_fixed="/usr/lib/games/nethack"
 # variable data to create (leave blank to skip) (may be equal to previous)
 playground_var="/var/games/nethack"
 # termcap/terminfo (copied recursively) (leave blank to skip)
-if [ -d "/etc/terminfo" ]; then
-  termdata="/etc/terminfo"
-elif [ -d "/usr/share/lib/terminfo" ]; then
-  termdata="/usr/share/lib/terminfo"
-else
-  termdata="/usr/share/terminfo"
-fi
-
 [ -f dgl-create-chroot.conf ] && . ./dgl-create-chroot.conf
+
+if [ -z "$termdata" ]; then
+	for dir in /etc/terminfo /usr/share/lib/terminfo /usr/share/terminfo; do
+		if [ -e "$dir/x/xterm" ]; then
+			termdata=$dir
+			break
+		fi
+	done
+	if [ -z "$termdata" ]; then
+		echo "Error: couldn't find terminfo definitions. Please specify in 'termdata' variable." >&2
+		exit 1
+	fi
+fi
 
 findlibs()
 {
 	for i in "$@"; do
 		# () to ignore errors
-		( ldd "$i" 2>/dev/null | awk '{ if ($2=="=>") print $3; }' )
+		( ldd "$i" 2>/dev/null | awk '{ if ($2=="=>" && $1!="linux-gate.so.1") print $3; }' )
 	done
 }
 findinpath()
@@ -128,7 +133,7 @@ fi
 if [ -n "$termdata" ]; then
 	mkdir -p $chroot_path`dirname $termdata`
 	if [ -d $termdata/. ]; then
-		cp -R $termdata/. $chroot_path$termdata
+		cp -LR $termdata/. $chroot_path$termdata
 	else
 		cp $termdata $chroot_path`dirname $termdata`
 	fi
